import { useMicrosoftAuth } from './useMicrosoftAuth';
import type { Memo, Session } from '../types';
import { outputModeLabels } from '../types';
import { memoToHtml } from '../lib/memoToHtml';

const GRAPH_BASE = 'https://graph.microsoft.com/v1.0';

export interface Notebook {
  id: string;
  displayName: string;
}

export interface NoteSection {
  id: string;
  displayName: string;
}

export function useOneNote() {
  const { getAccessToken } = useMicrosoftAuth();

  async function graphGet<T>(path: string): Promise<T> {
    const token = await getAccessToken();
    const res = await fetch(`${GRAPH_BASE}${path}`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    if (!res.ok) {
      throw new Error(`Graph API error ${res.status}: ${await res.text()}`);
    }
    const data = await res.json() as { value: T };
    return data.value;
  }

  async function getNotebooks(): Promise<Notebook[]> {
    return graphGet<Notebook[]>('/me/onenote/notebooks?$select=id,displayName');
  }

  async function getSections(notebookId: string): Promise<NoteSection[]> {
    return graphGet<NoteSection[]>(
      `/me/onenote/notebooks/${notebookId}/sections?$select=id,displayName`,
    );
  }

  async function createPage(sectionId: string, session: Session, memo: Memo): Promise<void> {
    const token = await getAccessToken();
    const date = new Date(memo.createdAt).toLocaleDateString('da-DK', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
    const title = session.title ?? 'MyMemo';
    const outputModeLabel = outputModeLabels[memo.outputMode];
    const paragraphs = memoToHtml(memo.content);

    const html = `<!DOCTYPE html>
<html>
  <head>
    <title>${title} — ${date}</title>
    <meta name="created" content="${memo.createdAt}" />
  </head>
  <body>
    <h1>${session.title ?? 'Untitled Session'}</h1>
    <p><em>Output mode: ${outputModeLabel} · Generated by MyMemo</em></p>
    <br />
    ${paragraphs}
  </body>
</html>`;

    const res = await fetch(`${GRAPH_BASE}/me/onenote/sections/${sectionId}/pages`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'text/html',
      },
      body: html,
    });

    if (!res.ok) {
      throw new Error(`Failed to create OneNote page: ${res.status} ${await res.text()}`);
    }
  }

  return { getNotebooks, getSections, createPage };
}
